# AGP 性能优化
android.dependency.excludeLibraryComponentsFromConstraints=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.useAndroidX=true